
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 25 00:26:35 CET 2022
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 30;
  public static final int READ = 10;
  public static final int CARET = 34;
  public static final int LSQUAREBRACE = 21;
  public static final int IDENT = 3;
  public static final int PLUS = 26;
  public static final int RBRACE = 20;
  public static final int RPAREN = 18;
  public static final int EQUAL = 25;
  public static final int SEMI = 31;
  public static final int CHAR = 4;
  public static final int GOTO = 16;
  public static final int RETURN = 7;
  public static final int COLON = 33;
  public static final int LBRACE = 19;
  public static final int LPAREN = 17;
  public static final int HASH = 13;
  public static final int INC = 23;
  public static final int COMMA = 32;
  public static final int RSQUAREBRACE = 22;
  public static final int EOF = 0;
  public static final int NUMBER = 5;
  public static final int DIV = 29;
  public static final int PROG = 6;
  public static final int DEC = 24;
  public static final int MINUS = 27;
  public static final int CONST = 15;
  public static final int FINAL = 11;
  public static final int MONKEY = 12;
  public static final int PRINT = 9;
  public static final int error = 1;
  public static final int NEW = 14;
  public static final int BOOL = 2;
  public static final int MUL = 28;
  public static final int VOID = 8;
}

